[package]
name = "spytools"
version = "0.3.0"
authors = ["Julia Evans <julia@jvns.ca>", "Ben Frederickson <github@benfrederickson.com>", "Adam Jensen <adam@acj.sh>"]
description = "Tools for spying on running processes"
license = "MIT"
repository = "https://github.com/rbspy/spytools"
edition = "2018"

[dependencies]
anyhow = "1.0.91"
goblin = "0.9.2"
lazy_static = "1.5.0"
libc = "0.2.161"
log = "0.4.22"
memmap2 = "0.9.5"
proc-maps = "0.4.0"
regex = "1.11.1"
remoteprocess = "0.5.0"
