name: CI
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  format:
    name: Check code formatting
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@984d158d699777abbaa79de23de3134e60c187fa # stable branch
      - name: Run cargo fmt
        run: |
          cargo fmt --all -- --check

  build:
    name: Build and test
    env:
      CARGO: cargo
      TARGET_FLAGS: --target ${{ matrix.target }}
      RUST_BACKTRACE: 1
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - linux
          - macos
          - windows
        include:
          - build: linux
            os: ubuntu-22.04
            run-tests: 'true'
            target: x86_64-unknown-linux-gnu
          - build: macos
            os: macos-10.15
            run-tests: 'true'
            target: x86_64-apple-darwin
          - build: windows
            os: windows-2019
            run-tests: 'true'
            target: x86_64-pc-windows-msvc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@984d158d699777abbaa79de23de3134e60c187fa # stable branch
      - name: Install Rust toolchain target
        run: rustup target add ${{ matrix.target }}
      - name: Cargo Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-cargo-
      - name: Build the library
        run: ${{ env.CARGO }} build --release --all-targets ${{ env.TARGET_FLAGS }}
      - name: Run tests
        timeout-minutes: 5
        run: ${{ env.CARGO }} test --release ${{ env.TARGET_FLAGS }}
        if: (runner.os == 'linux' || runner.os == 'windows') && matrix.run-tests == 'true'
      - name: Run tests
        timeout-minutes: 5
        run: sudo "PATH=$PATH" ${{ env.CARGO }} test --release ${{ env.TARGET_FLAGS }}
        if: runner.os == 'macOS' && matrix.run-tests == 'true'

  build-freebsd:
    name: Build and test (freebsd-x86_64)
    runs-on: macos-10.15
    timeout-minutes: 30
    strategy:
      matrix:
        box:
          - fbsd_12_2
    steps:
      - uses: actions/checkout@v3
      - name: Cache Vagrant box
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d
          key: ${{ matrix.box }}-vagrant-boxes-${{ hashFiles('ci/Vagrantfile') }}
          restore-keys: |
            ${{ matrix.box }}-vagrant-boxes-
      - name: Cache Cargo and build artifacts
        uses: actions/cache@v3
        with:
          path: build-artifacts.tar
          key: ${{ matrix.box }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ matrix.box }}-cargo-
      - name: Set up VM
        run: |
          ln -sf ci/Vagrantfile Vagrantfile

          if [ ! -d ~/.vagrant.d/boxes/rbspy-VAGRANTSLASH-FreeBSD-12.2-STABLE ]; then
            vagrant box add rbspy/FreeBSD-12.2-STABLE https://github.com/rbspy/freebsd-vagrant-box/releases/download/20220115-2/fbsd_12_2.box
          fi
          vagrant up ${{ matrix.box }}
      - name: Build and test
        run: vagrant ssh ${{ matrix.box }} -- bash /vagrant/ci/freebsd-build.sh
      - name: Retrieve build artifacts for caching purposes
        run: |
          vagrant ssh-config --host "default" > config.txt
          scp -F config.txt default:/vagrant/build-artifacts.tar .
          ls -ahl build-artifacts.tar

  release:
    name: Create draft release
    runs-on: ubuntu-22.04
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [build, build-freebsd]
    steps:
      - uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # v1.1.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          prerelease: false
