name: Publish release to crates.io

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publish crate
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # v1.0.6
        with:
          toolchain: stable
          override: true
      - run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish
